spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      repositories:
        enabled: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.ipd.platform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
